image:
  repository: ruanbekker/blockchain-btc
  tag: 22.0
  digest: sha256:103b753af622878df0fd792aa284a6fccbb159cc4481c0108abe75d96b520198
  pullPolicy: IfNotPresent

configuration:
  rpcuser: "user" # optional: if not quoted it will be generated
  txindex: 1
  server: 1
  network: testnet # required: (mainnet, regtest, signet or testnet) default: mainnet
  prune: 0
  disablewallet: 1
  passwordLength: 50 # this will be ignored if a passwordSecret is present
  rpcallowip: 0.0.0.0/0 
  # passwordSecret: "bitcoin-secrets" # use a existing secret and reference .password

persistence:
  accessMode: ReadWriteOnce
  size: 20G
  storageClass: gp2

resources:
  requests:
    cpu: 250m
    memory: 1G
  limits:
    cpu: 1000m
    memory: 1G
