replicaCount: 1

image:
  repository: ruanbekker/hostname
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: {}
      domain: "localdns.xyz"
      paths: [/]

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
