apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dogecoind.name" . }}
  labels:
    app: {{ template "dogecoind.name" . }}
    chart: {{ template "dogecoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: 
  dogecoin.conf: |
    datadir=/dogecoin/data
    printtoconsole={{ .Values.configuration.printtoconsole | default 1 }}
    rpcallowip={{ .Values.configuration.rpcallowip | default "0.0.0.0" }}
    prune={{ .Values.configuration.prune | default 0 }}
    # Additional configurations
    zmqpubrawblock=tcp://0.0.0.0:28332
    zmqpubrawtx=tcp://0.0.0.0:28333
    txindex={{ .Values.configuration.txindex }}
    server={{ .Values.configuration.server }}
    # Print to console (stdout) so that "docker logs dogecoind" prints useful information.
    disablewallet={{ .Values.configuration.disablewallet | default 1 }}
    onlynet=ipv4
    {{- if eq .Values.configuration.network "testnet" }}
    testnet=1
    [test]
    rpcbind={{ .Values.configuration.rpcbind | default "0.0.0.0" }}
    rpcport={{ .Values.configuration.rpcport | default 8332 }}
    port={{ .Values.configuration.port | default 8333 }}
    {{- else if eq .Values.configuration.network "mainnet" }}
    mainnet=1
    rpcbind={{ .Values.configuration.rpcbind | default "0.0.0.0" }}
    rpcport={{ .Values.configuration.rpcport | default 8332 }}
    port={{ .Values.configuration.port | default 8333 }}
    {{- end }}