apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dogecoind.name" . }}
  labels:
    app: {{ template "dogecoind.name" . }}
    chart: {{ template "dogecoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.configuration.passwordSecret }}
  # If passwordSecret is provided, fetch the password from the specified secret
  rpcpassword: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.configuration.passwordSecret).data "password" }}
  {{- else }}
    {{- if .Release.IsInstall }}
  # Generate new password if installing
  rpcpassword: {{ randAlphaNum (int .Values.configuration.passwordLength) | b64enc }}
    {{- else }}
  # Fetch existing password if not installing
  rpcpassword:  {{ index (lookup "v1" "Secret" .Release.Namespace "dogecoind").data "rpcpassword" }}
    {{- end }}
  {{- end }}
  {{- if .Release.IsInstall }}
  rpcuser: {{ .Values.configuration.rpcuser | default (randAlphaNum 8) | b64enc }}
  {{- else }}
    {{ if (.Values.configuration.rpcuser) }} 
  rpcuser:  {{ .Values.configuration.rpcuser | b64enc}}
    {{ else }}
  rpcuser:  {{ index (lookup "v1" "Secret" .Release.Namespace "dogecoind").data "rpcuser" }}
    {{ end }}
  {{- end }}