apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "litecoind.name" . }}
  labels:
    app: {{ template "litecoind.name" . }}
    chart: {{ template "litecoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}