{{- if .Values.sealedsecrets.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    {{- if eq .Values.sealedsecrets.scope "namespace-wide" }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{- else if eq .Values.sealedsecrets.scope "cluster-wide" }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{- end }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}-sealed-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
{{- range $key, $value := .Values.sealedsecrets.secrets }}
    {{ $key }}: {{ $value }}
{{- end }}
  template:
    metadata:
      annotations:
        {{- if eq .Values.sealedsecrets.scope "namespace-wide" }}
        sealedsecrets.bitnami.com/namespace-wide: "true"
        {{- else if eq .Values.sealedsecrets.scope "cluster-wide" }}
        sealedsecrets.bitnami.com/cluster-wide: "true"
        {{- end }}
      name: {{ .Release.Name }}-sealed-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
