apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiremock.fullname" . }}
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
data:
  api.json: |-
    {
      "request": {
        "method": "GET",
        "url": "/api/v1/users"
      },
      "response": {
        "status": 200,
        "fixedDelayMilliseconds": 50,
        "headers": {
          "Content-Type": "application/json"
        },
        "jsonBody": {
          "data": [{
            "id": "1",
            "username": "ruanb",
            "attributes": {
              "country": "South Africa",
              "fullName": "Ruan Bekker",
              "age": 34,
              "proffesion": "DevOps Engineer"
             }
          },
          {
            "id": "2",
            "username": "sarahm",
            "attributes": {
              "country": "Australia",
              "fullName": "Sarah Miller",
              "age": 31,
              "proffesion": "Teacher"
            }
          }]
        }
      }
    }
 