apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if eq .Values.deploymentStrategy "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
    {{- else if eq .Values.deploymentStrategy "Recreate" }}
    type: Recreate
    {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env: 
            {{- include "helpers.environment-variables" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          startupProbe:
            {{- if eq .Values.probes.startup.type "http" }}
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.probes.startup.port }}
            {{- else if eq .Values.probes.startup.type "exec" }}
            exec:
              command:
                {{- toYaml .Values.probes.startup.exec | nindent 16 }}
            {{- end }}
            failureThreshold: {{ .Values.probes.startup.failure_threshold }}
            periodSeconds: {{ .Values.probes.startup.period_seconds }}
          livenessProbe:
            {{- if eq .Values.probes.liveness.type "http" }}
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
            {{- else if eq .Values.probes.liveness.type "exec" }}
            exec:
              command:
                {{- toYaml .Values.probes.liveness.exec | nindent 16 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.liveness.initial_delay_seconds }}
            periodSeconds: {{ .Values.probes.liveness.period_seconds }}
          readinessProbe:
            {{- if eq .Values.probes.readiness.type "http" }}
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
            {{- else if eq .Values.probes.readiness.type "exec" }}
            exec:
              command:
                {{- toYaml .Values.probes.readiness.exec | nindent 16 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.readiness.initial_delay_seconds }}
            periodSeconds: {{ .Values.probes.readiness.period_seconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
